using AutoMapper;
using MessageService.API.Models;
using MessageService.API.Models.DTOs;

namespace MessageService.API.MappingProfiles
{
    public class MessageProfile : Profile
    {
        public MessageProfile()
        {
            // Маппинг из Message в MessageDto
            CreateMap<Message, MessageDto>()
                .ForMember(dest => dest.UserName, opt => opt.MapFrom(src =>
                    string.IsNullOrWhiteSpace(src.UserName) ? "Аноним" : src.UserName))
                .ForMember(dest => dest.Timestamp, opt => opt.MapFrom(src =>
                    src.Timestamp.ToString("yyyy-MM-dd HH:mm")));  // Форматирование даты до минут

            CreateMap<MessageDto, Message>()
                .ForMember(dest => dest.Timestamp, opt => opt.Ignore()) // Ignore the Timestamp field during mapping
                .ForMember(dest => dest.Id, opt => opt.Ignore()); // Ignore Id as it is usually generated by the database
        }
    }
}
